---
detectors:
  Attribute:
    exclude:
      - RDoc::Options#markdown_unknown_tags
  BooleanParameter:
    exclude:
      - RDoc::Generator::Markdown::CrossrefExtension#link
  ControlParameter:
    exclude:
      - RDoc::Generator::Markdown::Descriptions#method_link
      - RDoc::Generator::Markdown::Signatures#self.top_level_signature_separator?
  DuplicateMethodCall:
    exclude:
      - RDoc::Generator::Markdown::Paths#self.resolve_output_path_from
      - RDoc::Generator::Markdown::Signatures#self.split_signature_list
  FeatureEnvy:
    exclude:
      - RDoc::Generator::Markdown::Conversion
      - RDoc::Generator::Markdown::Descriptions
  LongParameterList:
    exclude:
      - RDoc::Generator::Markdown::CrossrefExtension#link
  TooManyStatements:
    max_statements: 12
  TooManyInstanceVariables:
    max_instance_variables: 5
  UtilityFunction:
    public_methods_only: true
