# For available configuration options, see:
#   https://github.com/testdouble/standard
ruby_version: 2.7
parallel: true
format: progress

ignore:
 - 'docs/example.rb'
 - '**/*':
    - Style/GlobalVars
