inherit_gem:
  yard-lint: lib/yard/lint/templates/strict_config.yml

AllValidators:
  Exclude:
    - '\.git'
    - ".erb_linters"
    - ".erb_linters/**/*"
    - "coverage"
    - "coverage/**/*"
    - "tmp"
    - "vendor/**/*"
    - "vendor"
    - "node_modules/**/*"
    - "spec/**/*"
    - "test/**/*"
    - "tmp/**/*"
    - "lib/rdoc/markdown/version.rb"
