usage: opensource

integration:
  name: minitest

includes:
  - lib
  - test

requires:
  - ./test/support/mutant_setup.rb

matcher:
  subjects:
    - RDoc::Generator::Markdown#anchor
    - RDoc::Generator::Markdown#class_dir
    - RDoc::Generator::Markdown#page_output_path
    - RDoc::Generator::Markdown#turn_to_path
